/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface ZReport {
  'totalProfit' : number,
  'totalRevenue' : number,
  'products' : Array<ZReportProduct>,
  'totalQuantity' : bigint,
}
export interface ZReportProduct {
  'purchasePrice' : number,
  'revenue' : number,
  'sellingPrice' : number,
  'productName' : string,
  'quantitySold' : bigint,
  'profit' : number,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string], boolean>,
  'addStock' : ActorMethod<[string, bigint, number], boolean>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'getSalesHistory' : ActorMethod<[], Array<[string, bigint, number, Time]>>,
  'getStockLevels' : ActorMethod<[], Array<[string, bigint]>>,
  'getZReport' : ActorMethod<[], ZReport>,
  'recordSale' : ActorMethod<[string, bigint, number, Time], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];