/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'addStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
  'getTodaySales' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'recordSale' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64, Time], [], []),
  'resetStocks' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'addStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
    'getTodaySales' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'recordSale' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64, Time], [], []),
    'resetStocks' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };