/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ZReportProduct = IDL.Record({
  'purchasePrice' : IDL.Float64,
  'revenue' : IDL.Float64,
  'sellingPrice' : IDL.Float64,
  'productName' : IDL.Text,
  'quantitySold' : IDL.Nat,
  'profit' : IDL.Float64,
});
export const ZReport = IDL.Record({
  'totalProfit' : IDL.Float64,
  'totalRevenue' : IDL.Float64,
  'products' : IDL.Vec(ZReportProduct),
  'totalQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getSalesHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64, Time))],
      ['query'],
    ),
  'getStockLevels' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getZReport' : IDL.Func([], [ZReport], ['query']),
  'recordSale' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, Time],
      [IDL.Bool],
      [],
    ),
  'resetInventory' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ZReportProduct = IDL.Record({
    'purchasePrice' : IDL.Float64,
    'revenue' : IDL.Float64,
    'sellingPrice' : IDL.Float64,
    'productName' : IDL.Text,
    'quantitySold' : IDL.Nat,
    'profit' : IDL.Float64,
  });
  const ZReport = IDL.Record({
    'totalProfit' : IDL.Float64,
    'totalRevenue' : IDL.Float64,
    'products' : IDL.Vec(ZReportProduct),
    'totalQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addStock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getSalesHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64, Time))],
        ['query'],
      ),
    'getStockLevels' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getZReport' : IDL.Func([], [ZReport], ['query']),
    'recordSale' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, Time],
        [IDL.Bool],
        [],
      ),
    'resetInventory' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };